name: Psykologiforbundet
favicon: null
layout_spectrum: 0.010564996860921383
typography_spectrum: 0.4985274588689208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.31665040319785476
  lightness: 0.3437002724967897
  saturation: 0.7991514066234231
  rhythmicContrast: 0.7430764678865671
purpose: []
